
DROP TABLE KHTEST;

CREATE TABLE KHTEST(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	ADDR VARCHAR2(1000) NOT NULL
);

SELECT NO, NAME, PHONE, ADDR
FROM KHTEST;

INSERT INTO KHTEST
VALUES(1, '멍멍이', '010-0000-0000', '서울');

SELECT NO, NAME, PHONE, ADDR
FROM KHTEST;
